### ISSUE TITLE
推荐使用nb自带的to_me rule

### ISSUE THREAD

**Issue by RShock** [TheLZY/nonebot_plugin_tuan_chatgpt#1]
这个rule可以同时触发at和对自己的称呼。虽然不清楚是否能对nb和真寻以外的机器人生效。
e.g.
```
from nonebot.rule import to_me
chat_service = on_message(rule=to_me(), priority=9)
```

.env.dev
```
NICKNAME = ["团子"]
```

**Comment by TheLZY** [comment]
感谢，有空我试试效果😊👍

**Comment by TheLZY** [comment]
这个应该也是利用的nonebot自带的转义功能，把nickname转义成to_me
问题是，只要message中存在nickname里的值就会回复，而不会对位置有反应
比如，包含团子的消息，像是 三彩团子 ，也会相应
（顺便一提对于telegram adapter的@事件又不会响应  就很迷）

我希望的是能够实现 nickname 在开头 or 任意位置的@事件 都可以回复
如果再在其中加一个 if 判定开头的感觉会很影响性能（

不过确实是个好思路！
似乎可以利用rule里面的_checker来达到效果
我再研究研究

**Comment by TheLZY** [comment]
不过对于paimon bot来说确实是可行的
 nickname 在开头 or 任意位置的@事件 都可以回复
（试图抄paimon bot的源码 发现写得很简单）
我怀疑是我telegrambot初始化的问题 他只能回复私聊不能回复群聊的@事件 / nickname
我改改试试

ref:
paimeng bot的run_cmd写法
```
run_cmd = on_command(
    'cmd',
    permission=SUPERUSER,
    rule=to_me(),
    priority=1,
    block=True,
    state={
        'pm_name': 'bot_cmd',
        'pm_description': '运行终端命令，需超级用户权限',
        'pm_usage': '@bot cmd<命令>',
        'pm_priority': 4,
    },
)
```

凑，原来Telegram adaper 对于 to_me() 的处理有点问题
那其他的 bot 应该可以对规则用 or 来应付一下

**Comment by RShock** [comment]
这里可能就要用nb的[on_regex](https://v2.nonebot.dev/docs/tutorial/plugin/create-matcher)适配器或者[rule](https://v2.nonebot.dev/docs/advanced/rule)了
另外就我测试来看，to_me其实只会对开头的名字进行响应。文中的名字是没有反应的。也就是完美满足要求。
反而是如果想让bot对文中名字也有反应，似乎更麻烦一些

**Comment by TheLZY** [comment]
消息触发器暂时改成

    on_message(startswith("团子", ignorecase = True) or to_me(), priority = 99, block = False)

#[d725aa](https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt/commit/d725aa262f62de7751f9f67b9b5c399b655f5976)

能够回应团子开头的消息
不过 `to_me()` 好像还是有问题 不会回应@事件

有点奇怪

明明能够回应 `派蒙 cmd echo aa` 的

估计是哪里被block了？
我再试试

**Comment by TheLZY** [comment]
能试试您的测试代码嘛 我发现我最近的 @ 测试一次都没成功过 😥

我开始怀疑是 on_message 会被block的问题了，但是控制台又没显示有别的插件被触发

**Comment by RShock** [comment]
我对这个or写法并不了解，猜想这个写法不成立所以to_me才不能触发的。
我只熟悉1楼的写法

**Comment by TheLZY** [comment]
好像确实 我看到 rule 源码里有
```
    def __or__(self, other: object) -> NoReturn:
        raise RuntimeError("Or operation between rules is not allowed.")
```
😪
虽然没报错 想来也没进行第二项检查
那我再回去试试您的方法叭
非常感谢帮助 🤗

**Comment by TheLZY** [comment]
造了个checker的轮子
现在可以同时用 @ / 团子 唤醒了 😄

#https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt/commit/6ce20a41e3ee045c212fdb83fa5a369617efad30
```
async def chat_checker(event: MessageEvent) -> bool:
    # 检查 是否以团子开头 / to_me. 可能会造成一点性能问题
    res = str(event.get_message())[:2]  == '团子' or event.is_tome()
    return res

```
