### ISSUE TITLE
插件未启用

### ISSUE THREAD

**Issue by Marked1937** [TheLZY/nonebot_plugin_tuan_chatgpt#2]
![image](https://user-images.githubusercontent.com/128020719/225527699-307ec356-e53f-473f-a1a9-86df0183174f.png)

**Comment by TheLZY** [comment]
啊，怪了，不知道为啥多了个参数，马上修

**Comment by TheLZY** [comment]
https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt/commit/28e516332765419d7bcb44f5e8906ecf8c894f05 

修好了，请更新一下 😉

**Comment by TheLZY** [comment]
（ 我就说为啥有群友说私聊没回 😂
