### ISSUE TITLE
无法导入'nonebot_plugin_tuan_chatgpt'。

### ISSUE THREAD

**Issue by 941675268** [TheLZY/nonebot_plugin_tuan_chatgpt#3]
![QQ截图20230316205247](https://user-images.githubusercontent.com/128051413/225623295-e826efb5-e054-44a1-8fcd-8abda484a73e.png)
![QQ截图20230316205356](https://user-images.githubusercontent.com/128051413/225623310-834e100a-6d7f-4a9e-aaf4-c30f4528c152.png)
![QQ截图20230316205514](https://user-images.githubusercontent.com/128051413/225623313-3e46bcc8-a09d-4b99-a907-d175b7924c04.png)
不知道为什么插件无法导入使用，附上.ven文件图片（第二张）和pyproject(第三张)

**Comment by TheLZY** [comment]
看起来好像是pydantic导入的问题？
我回家后研究研究
顺便，可以复制一下值吗，我看看会不会是字典的问题

对了，还有大兄弟你的api泄露了，最好遮一下（

**Comment by 941675268** [comment]
你说的值是哪个文件的值，API的话，没事，我已经注销了，谢谢提醒。

**Comment by TheLZY** [comment]
测试了一下，pydantic处理dict格式的数据确实容易出问题
环境变量我重新换了一种写法，现在应该没啥问题了
https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt/commit/a05f84820bc890cb6550c9652a41a0632f915fe7
请升级一下再试试🤗

感谢提醒报错！😋

**Comment by 941675268** [comment]
更新完之后会出现：Error communicating with OpenAI
首先我排查了梯子问题，因为我同时还运行了GPT-3官方的接口，是可以正常使用API的
然后我排除了API端口无法使用的问题，我更换了四条新的API秘钥，还是会出现上述报错
所以我在想，有没有可能是插件内部的问题

**Comment by 941675268** [comment]
非常感谢您在前面能快速回复我，解决我遇到的难题

**Comment by TheLZY** [comment]
怪了，这种报错大概率都是梯子的问题
能看看详细的报错信息吗？
以及http/https地址的写法？

我记得写了一个团子看看位置的命令，你用这个能显示位置吗？

还有aiohttp的版本？requirements里面写了要最新的3.8.4，老版本代理的时候容易出现问题

对了，记得使用最新的版本
https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt/commit/bc83c05922f61f257e3d91b3ea27247e3f16f0fa
之前的写法忘了改看位置的命令（

**Comment by 941675268** [comment]
![image](https://user-images.githubusercontent.com/128051413/226109303-46ce8299-f2c9-46bb-b462-ebdda3fa2518.png)
![image](https://user-images.githubusercontent.com/128051413/226109658-b8b6056a-2436-470b-aaae-10951cf49cb9.png)
这里还演示了同时挂两个机器人进行对比，用的是来自一个账号的四个不同的API，所以可以排除API和梯子的问题。但本身插件在运行的时候没有报错，只有在交流是才会返回API异常

**Comment by TheLZY** [comment]
参数的写法似乎没有问题

怪了，我也是这么写的，没有问题啊（
之前倒是有异步或者aiohttp版本的问题   https://github.com/nonebot/nonebot2/issues/1784
要不然你试试跑一下这个脚本？我看看具体报错在哪个位置

[test_acre.txt](https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt/files/11008688/test_acre.txt)

记得填一下api和代理，然后把txt改成py后直接 python test_acre.py 就行
如果nonebot用了虚拟环境记得切换
如果控制台显示
response without async
XXXX（结果）
然后有报错

可以 pip show aiohttp 一下吗
我看看会不会是aiohttp的问题

**Comment by 941675268** [comment]
![QQ截图20230319163625](https://user-images.githubusercontent.com/128051413/226164935-28622caf-a7f3-49f3-8999-8f54d1b7c9ab.png)
![QQ截图20230319162919](https://user-images.githubusercontent.com/128051413/226164940-4beff396-0cf9-4c91-ac7d-9e946c33d800.png)

**Comment by 941675268** [comment]
![QQ截图20230319162919](https://user-images.githubusercontent.com/128051413/226166671-8849d0b5-ea40-4f7c-a867-baf0efd332b2.png)
![QQ截图20230319163625](https://user-images.githubusercontent.com/128051413/226166675-9fb4f0db-cbd0-4bc5-947d-9d23b81627ce.png)

**Comment by TheLZY** [comment]
那现在看来是直接调用的时候没问题，但是使用异步的时候会出问题
（好像最开始大家都有这个问题来着
不过那时候解决方案是 升级ssl / 升级aiohttp / 添加 trustenv来着
我看看有没有什么方便一点的解决方案

https://github.com/openai/openai-python/issues/278

**Comment by TheLZY** [comment]
等等，127.0.0.1:8080 是你的代理地址吗？
这里好像显示的是到本地的连接有问题，不是到openai的连接
openai连接报错会写 api.openai.com:443 之类的

要不你试试看看代理有没有接收到消息？或者proxy只用 http / https 里的一个试试？

**Comment by 941675268** [comment]
![QQ截图20230319192257](https://user-images.githubusercontent.com/128051413/226174959-c64dd70e-d4f4-46fe-aa5c-e1dc69df32db.png)
![QQ截图20230319193905](https://user-images.githubusercontent.com/128051413/226174960-94b38778-4b38-41ad-b2cf-3e3d59bf31a0.png)
![QQ截图20230319194601](https://user-images.githubusercontent.com/128051413/226174961-90cb74a0-c286-46a3-83f3-24244ebf6ec0.png)
![QQ截图20230319195542](https://user-images.githubusercontent.com/128051413/226174962-d35a5b5c-1da8-4500-8356-76b3159eddd0.png)
![QQ截图20230319202326](https://user-images.githubusercontent.com/128051413/226174963-44d7d40b-a4b0-4a88-8126-a686d097dafc.png)
![QQ截图20230319202407](https://user-images.githubusercontent.com/128051413/226174965-aabb429a-a17b-4871-9f01-a802f7e3ab0f.png)
QQ与go cqhttp、nonebot之间的链接应该是正常的，能监听到消息。我更换了代理地址和端口也无法解决上述问题。
也许值得注意的是loop循环的报错。如最后一张图所示

**Comment by TheLZY** [comment]
你这个图是一次跑的结果的吗？
按照你图里的配置，我猜测4554是运行测试脚本时梯子的接口，10809是运行插件时梯子的接口

但是脚本报错信息里写的是连接4554的时候出现了问题
但是按照测试脚本的情况来看，更像是异步调用的时候出问题了
因为测试脚本其实我测试了两种方式，
一种是不利用协程的，这里你通信成功了
![image](https://user-images.githubusercontent.com/32624562/226176054-ebfe4a53-8c1f-44ea-917e-f4ece6d3aea1.png)

然后第二种是利用协程的，在创建协程的时候就出现了warning（这是python版本的问题，python3.11可能有更推荐的写法）
但是真正的error出现在连接代理时候的
![image](https://user-images.githubusercontent.com/32624562/226176362-2db88cc4-eb95-4941-82c5-7e493f8fc99c.png)

我推测是python版本造成的aiohttp的连接方式问题，等我造个虚拟环境测试下（

**Comment by TheLZY** [comment]
怪了，新建了个虚拟环境，并不会有什么问题（
那么问题就出现在了异步调用时的代理上
（因为同步调用很简单，requests 对代理的支持很好，但是异步调用需要用aiohttp等一大堆库，所以确实很容易出问题）

也许要关注一下能跑的那个插件
她有开源码？
或者，能跑的那个插件有使用协程的api吗？
（就是通信部分用的是 openai.ChatCompletion.**create** 还是 openai.ChatCompletion.**acreate**, 或者是直接用的requests？）

当时一大堆chatgpt插件都反应异步有问题，估计确实openai在写异步的时候哪儿没考虑兼容性

**Comment by 941675268** [comment]
能运行的那个是直接直接用python写出来的，直接链接官方给的API，不是在nonebot上运行的，你看看能不能打开这个链接下载：https://lucent.blog/?p=118  如果不能的话，可以联系我Q：941675268，我将文件传给你

**Comment by 941675268** [comment]
那可能是我电脑配置出了问题（无奈）

**Comment by 941675268** [comment]
我记得我现在运行的py版本好像是10的，不是最新的11

**Comment by TheLZY** [comment]
![image](https://user-images.githubusercontent.com/32624562/226208296-b5e40401-c486-4c8f-a143-99b4664016d7.png)
看了一眼，他确实没有使用异步 😥
不使用异步有一个坏处，就是会卡住别的程序，一次只能处理一条对话。

如果要一个一个排查错误的话，可以先试试我更新了一下的脚本
（主要通信都在测试脚本里了 脚本里能跑通那插件应该就不会有问题）
我更改了一下启动协程的方式，现在应该不会报warning了
注意填进去你的 api key 以及梯子地址
（可以不先下载，推荐用最下面的方法）
[test_acre.txt](https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt/files/11012339/test_acre.txt)


正常情况下，应该两种方式都能触发
![image](https://user-images.githubusercontent.com/32624562/226208825-06bf2598-506d-494c-be45-28c81506c35d.png)


然后查看一下各个包的版本
`pip list`
或者你的环境里包比较多的话，可以只看有关的
`pip show aiohttp aiosignal async-timeout certifi idna openai urllib3 wincertstore `

我的包：
```
pip list
Package            Version
------------------ ---------
aiohttp            3.8.4
aiosignal          1.3.1
async-timeout      4.0.2
attrs              22.2.0
certifi            2022.12.7
charset-normalizer 3.1.0
colorama           0.4.6
frozenlist         1.3.3
idna               3.4
multidict          6.0.4
openai             0.27.2
pip                23.0.1
requests           2.28.2
setuptools         65.5.0
tqdm               4.65.0
urllib3            1.26.15
wheel              0.37.1
wincertstore       0.2
yarl               1.8.2
```

或者如果想方便一点，可以使用poetry来一键控制版本
[chatgpt__debug.zip](https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt/files/11012392/chatgpt__debug.zip)

里面有一个测试脚本的 test_acre.py 文件（记得添加api和代理地址）和2个 poetry的版本文件，可以用 `poetry install`来固定版本
如果没有poetry的话可以直接pip下载  `pip install poetry`

现在可能的问题大概是：版本问题，证书问题和梯子问题。
如果你的梯子软件能够看到有没有接收到消息就最好了
