### ISSUE TITLE
一直说网不好

### ISSUE THREAD

**Issue by hahahahutao** [TheLZY/nonebot_plugin_tuan_chatgpt#4]
如何解决 

![微信截图_20230319132300](https://user-images.githubusercontent.com/128276365/226155581-ea4a08da-ea17-4eba-9d61-6f4d726b1411.png)
![微信截图_20230319132341](https://user-images.githubusercontent.com/128276365/226155584-b70ce90d-40d0-4539-b1bd-79574adedce6.png)
![微信截图_20230319132409](https://user-images.githubusercontent.com/128276365/226155586-6008ae25-5c5c-4ec8-9548-484a5f4d235f.png)

**Comment by TheLZY** [comment]
升级一下？ 这个报错是前几个版本的了，那时候梯子的写法还不是这样😂

**Comment by hahahahutao** [comment]
谢谢，解决啦

**Comment by Nenot233** [comment]
![image](https://user-images.githubusercontent.com/108965579/226559631-d1b0b84a-d5d3-47da-b4b9-9cfc669b69ef.png)
![image](https://user-images.githubusercontent.com/108965579/226559693-0a95059f-d7a3-442c-8714-883a2fb8a8ef.png)
我也遇到这个问题

**Comment by TheLZY** [comment]
> ![image](https://user-images.githubusercontent.com/108965579/226559631-d1b0b84a-d5d3-47da-b4b9-9cfc669b69ef.png) ![image](https://user-images.githubusercontent.com/108965579/226559693-0a95059f-d7a3-442c-8714-883a2fb8a8ef.png) 我也遇到这个问题

要不你试试 `团子看看位置` 看看代理是否启用
然后更新一下？ 后面重写了报错方式和代理方式，所以以前的不适用了

**Comment by Nenot233** [comment]
'Config' object has no attribute 'chat_proxy_address'！
我的代理地址格式错误了吗？

**Comment by TheLZY** [comment]
> 'Config' object has no attribute 'chat_proxy_address'！ 我的代理地址格式错误了吗？

是这样的，我更新了一下代理方式，你看看readme，现在应该需要和你之前的图里的一样用chat_proxy_address_http (s)
按理来说如果插件也更新了就不会有啥问题？
而且更新了后他会报详细的错误，还有问题你可以带着报错来

**Comment by Nenot233** [comment]
> > 'Config' object has no attribute 'chat_proxy_address'！ 我的代理地址格式错误了吗？
> 
> 是这样的，我更新了一下代理方式，你看看readme，现在应该需要和你之前的图里的一样用chat_proxy_address_http (s) 按理来说如果插件也更新了就不会有啥问题？ 而且更新了后他会报详细的错误，还有问题你可以带着报错来

![image](https://user-images.githubusercontent.com/108965579/226617688-feb82666-bd9b-413d-80b0-0b6dca4362b8.png)
![image](https://user-images.githubusercontent.com/108965579/226617751-ab3b9ae1-0db4-497c-b747-0eafc947662a.png)
插件是今天更新的

**Comment by TheLZY** [comment]
https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt/blob/master/nonebot_plugin_tuan_chatgpt/config.py
里面确实没有  chat_proxy_address 啊
你是咋更新的？ 能看到版本或者源码吗？（如果是pip安装的应该可以`pip show nonebot_plugin_tuan_chatgpt` 看版本）

按理来说看位置报这个错已经在这个commit里改了
https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt/commit/bc83c05922f61f257e3d91b3ea27247e3f16f0fa
也发布过了
[v0.2.3](https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt/releases/tag/v0.2.3)

~~如果是  v0.2.3 应该是不会报这个错的~~

emmmmm，确实是我的问题，下面的函数忘了改（

晚上回去就改（

**Comment by TheLZY** [comment]
> > > 'Config' object has no attribute 'chat_proxy_address'！ 我的代理地址格式错误了吗？
> > 
> > 
> > 是这样的，我更新了一下代理方式，你看看readme，现在应该需要和你之前的图里的一样用chat_proxy_address_http (s) 按理来说如果插件也更新了就不会有啥问题？ 而且更新了后他会报详细的错误，还有问题你可以带着报错来
> 
> ![image](https://user-images.githubusercontent.com/108965579/226617688-feb82666-bd9b-413d-80b0-0b6dca4362b8.png) ![image](https://user-images.githubusercontent.com/108965579/226617751-ab3b9ae1-0db4-497c-b747-0eafc947662a.png) 插件是今天更新的


改好了
https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt/commit/9f88902ebe48470b283e080c3bd847cd5317fecf

升级到最新版本 v0.2.4 应该就没问题了

**Comment by Nenot233** [comment]
赛博旅游失败！都怪Cannot connect to host ipapi.co:443 ssl:default [参数错误。]！
![image](https://user-images.githubusercontent.com/108965579/226782970-52bef668-f9d4-4d47-b13b-dfc63ddf277d.png)

**Comment by TheLZY** [comment]
> 赛博旅游失败！都怪Cannot connect to host ipapi.co:443 ssl:default [参数错误。]！ ![image](https://user-images.githubusercontent.com/108965579/226782970-52bef668-f9d4-4d47-b13b-dfc63ddf277d.png)

啊这，这是使用代理失败了吗
clash日志里面有写什么嘛？
以及，你的aiohttp的版本是咋样的？
低版本的（比如3.7） 对https的代理有点问题

或者你试试运行这个测试脚本，我看看报什么错

[chatgpt_debug.zip](https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt/files/11039815/chatgpt_debug.zip)

里面有一个测试脚本的 test_acre.py 文件（记得添加api和代理地址）和2个 poetry用的 的版本文件
运行py文件直接python run它就行，如果使用了虚拟环境的记得切换

如果运行报错的话可以先用 http 代理测试一下是否是ssl的问题
然后考虑一下是不是版本的问题
可以用 `poetry install` 来固定版本
如果没有poetry的话可以直接pip下载 `pip install poetry`

**Comment by TheLZY** [comment]
> 赛博旅游失败！都怪Cannot connect to host ipapi.co:443 ssl:default [参数错误。]！ ![image](https://user-images.githubusercontent.com/108965579/226782970-52bef668-f9d4-4d47-b13b-dfc63ddf277d.png)

突然想起来，有一个urllib3相关的问题，我当初也遇到过这个，修改一下版本就好了
`pip install urllib3==1.25.11`

https://zhuanlan.zhihu.com/p/350015032

**Comment by Nenot233** [comment]
应该是aiohttp版本过高导致无法使用本插件

**Comment by TheLZY** [comment]
> 应该是aiohttp版本过高导致无法使用本插件

原来如此
瞬间就变得合理了起来
