### ISSUE TITLE
代理地址

### ISSUE THREAD

**Issue by FFKalo** [TheLZY/nonebot_plugin_tuan_chatgpt#6]
想问下怎么创建一个稳定的梯子
https://github.com/Ice-Hazymoon/openai-scf-proxy
我按这个教程搭建了代理地址，试了一下地址是能用的
但不能用于这个nonebot插件，不明白是什么原因

**Comment by TheLZY** [comment]
这个按理来说是端口转发，将你的信息转发给openai
所以要修改的是 api 的 url   `openai.api_base`，不是proxy

如果直接用梯子比较麻烦的话，可以考虑把这个功能加上去

**Comment by TheLZY** [comment]
https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt/commit/48ab886072505f62ef6b1963dfd32e20a7f476dc

增加了api转发支持
可以照着readme里面的参数设置方式试试

**Comment by FFKalo** [comment]
非常感谢，能够正常使用了
我这里chat_api_address的填写样式是https://service-xxxxxxxx.sg.apigw.tencentcs.com/v1

**Comment by TheLZY** [comment]
感谢测试！
