### ISSUE TITLE
设置了蕾姆的名称以后但启发还是团子呢

### ISSUE THREAD

**Issue by DragonSauce** [TheLZY/nonebot_plugin_tuan_chatgpt#7]
![图片](https://user-images.githubusercontent.com/42651551/233854785-c16d14ed-ff64-4f8b-95dd-daf9ba65094c.png)
![图片](https://user-images.githubusercontent.com/42651551/233854793-27aacbcd-2f58-4c80-942b-58eea75d063a.png)

**Comment by TheLZY** [comment]
啊，我当初写的时候是基于LittlePaimon的，那可能别的机器人或者直接用nonebot的话 nickname不会自动转义成at

emmmm，最近有在思考这个规则怎么写，应该几天后会适配一下（

**Comment by DragonSauce** [comment]
那现在想改的话可以怎么改呢，我该那个第一个选项团子的话改成其他的就不唤醒了

**Comment by DragonSauce** [comment]
好的，有更新了以后麻烦在通知我谢谢！

**Comment by TheLZY** [comment]
更新啦
https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt/commit/4a5f29e1960f92f2646874780bcf07d6f3502c96

**Comment by DragonSauce** [comment]
那团子的启发词怎么删呢

**Comment by TheLZY** [comment]
不用删，现在没有默认的了（

**Comment by XiaoLong2333** [comment]
那就是说设定了昵称以后，雷姆跟团子都会触发

**Comment by DragonSauce** [comment]
更新以后现在雷姆跟团子都会触发机器人

**Comment by TheLZY** [comment]
啊，我的问题，pip源忘了撤掉beta标了（
这下应该好了

**Comment by DragonSauce** [comment]
问一下，现在还是pip更新了以后默认的团子，跟设定的雷姆都会触发，不知道怎么回事，不能把团子替换成雷姆或者是替换成机器人的名字

**Comment by TheLZY** [comment]
不该啊，现在我直接用的nonebot内置的tome了，他会读取你设置的变量nickname
会不会是虚拟环境的问题？你pip更新的时候是在nonebot的python环境里更新的吗？

**Comment by DragonSauce** [comment]
那我重新获取一下看看，现在0.4.1版本是最新的吗

**Comment by TheLZY** [comment]
是的

**Comment by DragonSauce** [comment]
更新到0.4.1 说雷姆没有反应（哭了）+斜杠也没有

**Comment by DragonSauce** [comment]
![图片](https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt/assets/42651551/c95d2da2-8e5e-4f66-a720-99e27faed32d)

**Comment by DragonSauce** [comment]
看起来要@才能触发

**Comment by DragonSauce** [comment]
![图片](https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt/assets/42651551/6410b9c8-22fb-4167-abb9-f4508b7321a5)
配置如下

**Comment by TheLZY** [comment]
假粉丝！

![image](https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt/assets/32624562/b9539945-aab3-459d-a0f2-5c477a9e6774)

![image](https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt/assets/32624562/55d52a3d-b7a0-48e0-be22-0f02d2b45b4d)

**Comment by DragonSauce** [comment]
（捂脸哭）好吧真无奈了可能联想的时候配置的时候是微软的输入法就没仔细看

**Comment by TheLZY** [comment]
![9( TJ~%) 3ZPJ9`XAAHN@D](https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt/assets/32624562/bab60246-1cb6-4fb3-a4f6-a90405c0336c)

**Comment by DragonSauce** [comment]
眼瞎了属于是（悲）
![图片](https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt/assets/42651551/32426697-1d3a-46ef-946d-5ee8cb2e55dc)
