### ISSUE TITLE
提一个小小的建议

### ISSUE THREAD

**Issue by SeeWhyRan** [TheLZY/nonebot_plugin_tuan_chatgpt#8]
增加一个指令，让机器人重新开启一个新的对话。哈哈哈这样如果出现“性冷淡”了也可以手动刷新了....

**Comment by TheLZY** [comment]
有道理！确实可以

**Comment by SeeWhyRan** [comment]
更新了这个功能可以麻烦踹我一脚吗哈哈

**Comment by TheLZY** [comment]
更新啦 
https://github.com/TheLZY/nonebot_plugin_tuan_chatgpt/commit/4a5f29e1960f92f2646874780bcf07d6f3502c96

**Comment by SeeWhyRan** [comment]
好耶！
