### ISSUE TITLE
大佬大佬，新人求教

### ISSUE THREAD

**Issue by DTR3912** [TheLZY/nonebot_plugin_tuan_chatgpt#9]
请问您知道用真寻bot的话，生成的.env配置文件在哪吗

**Comment by TheLZY** [comment]
没用过，不知道（
按理来说一般和bot.py同级？

**Comment by TheLZY** [comment]
https://hibikier.github.io/zhenxun_bot/docs/installation_doc/install_zhenxun.html

不是有写吗

启动真寻，会在 configs 和 data/configs 目录下生成各种配置文件
```
python3 bot.py
# or
python bot.py
```

打开 configs/config.yaml，里面包含的是各种插件的配置项，填写完毕后重启真寻Bot

按理来说，在这个 .yaml里面填也可以

**Comment by DTR3912** [comment]
> https://hibikier.github.io/zhenxun_bot/docs/installation_doc/install_zhenxun.html
> 
> 不是有写吗
> 
> 启动真寻，会在 configs 和 data/configs 目录下生成各种配置文件
> 
> ```
> python3 bot.py
> # or
> python bot.py
> ```
> 
> 打开 configs/config.yaml，里面包含的是各种插件的配置项，填写完毕后重启真寻Bot
> 
> 按理来说，在这个 .yaml里面填也可以

确实是这么写的，但是没有啊，有的插件会生成配置文件，有的没有，好像适配过才会有，我也不清楚

**Comment by DTR3912** [comment]
> 

configs，data里都找了，.env，.env.dev，bot.py都找了，我能想得到都找过了，没看到生成，明天试试自己填进去能不能用吧。还是谢谢大佬了😊

**Comment by TheLZY** [comment]
按理来说他生成的只有config文件，里面的东西得自己填，没填就按照默认的配置来（
